server:
  port: 9996
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.200:3306/buildingblock_base?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: getf
    password: 111111
getf:
  buildingblock:
    infrastucture:
      fastdev:
        public-interceptor-class-names: [com.getf.buildingblock.infrastructure.fastdev.config.interceptor.OperationInfoInterceptor]
        table-configs:
          - tableName: sys_user
            interceptorClassNames: [com.getf.buildingblock.base.interceptor.UserInterceptor]
            getConfig:
              ignoreFields: [password]
            queryConfig:
              ignoreFields: [password]
          - tableName: sys_modular
            queryConfig:
              sql: SELECT c.*, p.name parent_name FROM sys_modular c LEFT JOIN sys_modular p ON c.parent_id=p.id

